name: gh-crawl-dvwa

on: workflow_dispatch
#on:
#  push:
#    branches:
#      - crawler
#      - har-file
#      - swagger
#      - brokencrystals
#  pull_request:
#    branches: [main]
#  schedule:
#    - cron: "0 0 * * THU"

jobs:
  wait_for:
    name: Wait for any issues, gh-int + code_scanning_alerts on
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Scan Start
        id: start
        uses: NeuraLegion/run-scan@release
        with:
          api_token: ${{ secrets.BRIGHT_TOKEN}}
          hostname: eu.brightsec.com
          name: DVWA - SDLC - CICD - Github Actions - Crawl-HAR Scan -  ${{ github.sha }}
          discovery_types: |
            [ "crawler"]
          crawler_urls: |
            [ "https://dvwa2.neuralegion.com/" ]
        
      - name: Wait for breakpoint
        id: wait
        uses: NeuraLegion/wait-for@release
        with:
          api_token:  ${{ secrets.BRIGHT_TOKEN }}
          hostname: eu.brightsec.com
          scan: ${{ steps.start.outputs.id }}
          code_scanning_alerts: true
          github_token: ${{ secrets.KEY_GITHUB }}


